# Generated by Django 4.0.1 on 2022-02-05 05:30

from django.db import migrations, models
import django.db.models.deletion
import places.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Здесь заголовок', max_length=256, unique=True, verbose_name='Заголовок')),
                ('description_short', tinymce.models.HTMLField(blank=True, help_text='Здесь краткое описание места', verbose_name='Краткое описание')),
                ('description_long', tinymce.models.HTMLField(blank=True, help_text='Здесь полное описание места', verbose_name='Полное описание')),
                ('longitude', models.FloatField(verbose_name='Широта')),
                ('latitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Точка на карте',
                'verbose_name_plural': 'Все точки на карте',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=places.models.get_file_path, verbose_name='Картинка')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер картинки')),
                ('point', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.point')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Все изображения',
                'ordering': ['position'],
            },
        ),
    ]
