# Generated by Django 4.0.1 on 2022-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('images', models.JSONField()),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('coordinates', models.JSONField()),
            ],
        ),
    ]
